{% set name = "oslo.serialization" %}
{% set version = "2.20.0" %}
{% set sha256 = "fca6fbb350d560aab8a4fdc9a1128dac3b1d38b2fc9bf5ad22136ae090854802" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr

  run:
    - python
    - six

test:
  imports:
    - oslo_serialization

about:
  home: https://docs.openstack.org/oslo.serialization/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Oslo Serialization library'
  description: | 
    The oslo serialization library provides support for representing objects 
    in transmittable and storable formats, such as JSON and MessagePack. 

extra:
  recipe-maintainers:
    - brainstorm 
